name: hyper_ui
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  badges: ^3.1.1
  blur: ^3.1.0
  cached_network_image: ^3.2.2
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.2
  custom_clippers: ^2.0.0
  dio: ^5.0.1
  dotted_border: ^2.0.0+3
  faker_dart: ^0.1.11
  file_picker: ^5.2.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_image_compress: ^2.0.3
  flutter_map: ^4.0.0
  flutter_markdown: ^0.6.12
  flutter_rating_bar: ^4.0.1
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^2.0.5
  freezed_annotation: ^2.1.0
  geolocator: ^9.0.2
  google_fonts: ^4.0.4
  image_picker: ^0.8.5+3
  intl: ^0.18.1
  json_annotation: ^4.7.0
  material_design_icons_flutter: ^6.0.7096
  path_provider: ^2.0.11
  permission_handler: ^10.0.2
  qr_flutter: ^4.0.0
  rex: ^1.0.5
  syncfusion_flutter_charts: ^21.2.4
  url_launcher: ^6.1.6
  uuid: ^3.0.6
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
